name: main
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [ 'jest' ]
    steps:
      - uses: actions/checkout@v3
      - name: Test Package
        uses: dmeents/maestro/src/github-actions/test-standard
        with:
          testSuite: ${{ matrix.suite }}

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Build semantic-release-yarn
        uses: dmeents/maestro/src/github-actions/build-standard
        with:
          packageName: semantic-release-yarn

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Get latest code
        run: git pull origin main
      - name: Release @dmeents/semantic-release-yarn
        uses: dmeents/maestro/src/github-actions/release-standard
        with:
          packageName: semantic-release-yarn
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GH_TOKEN }}
